### ISSUE TITLE
`certificate:UNAVAILABLE` appears in otto fashion categories

### ISSUE THREAD

**Issue by BigDatalex** [calgo-lab/green-db#119]
I just noticed that due to the last changes the `UNAVAILABLE` certificate shows up also in fashion categories. Not sure if that is a problem, but I thought it's a good idea to discuss that and be aware of it.

For example the following query:
`SELECT COUNT(id) AS "count", category FROM "green-db" WHERE "sustainability_labels" && '{certificate:UNAVAILABLE}'::TEXT[] AND "timestamp" = (SELECT MAX("timestamp") FROM "green-db") GROUP BY category Order BY "count" Desc;`

returns (top 5):
"count"	"category"
"11573"	"SHOES"
"5473"	"UNDERWEAR"
"3640"	"HEADPHONES"
"1496"	"LAPTOP"
"1093"	"JACKET"

And regarding the #118 we should discuss whether we want to export products with that "label" to zenodo.

**Comment by itrajanovska** [comment]
Good point @BigDatalex , but I think this might be a biproduct of their html update which happened in the same, I'm going to inspect that manually on several htmls from the fashion products.
In that case it might be better to return unavailable only if the products come from a certain merchant & category, what do you think?

**Comment by BigDatalex** [comment]
I think the best would be to have something working independent from the product category. Maybe we can access the `request.meta` within the extractor and check if it includes the `SUSTAINABILITY_FILTER`. We would then allow UNAVAILABLE only for products that were retrieved without using the `SUSTAINABILITY_FILTER`.

https://github.com/calgo-lab/green-db/blob/7ab12c99ef0a6360540dbcc7129fa757f6235312/scraping/scraping/spiders/_base.py#L307-L314

**Comment by itrajanovska** [comment]
> @itrajanovska I think the best would be to have something working independent from the product category. Maybe we can access the `request.meta` within the extractor and check if it includes the `SUSTAINABILITY_FILTER`. We would then allow `UNAVAILABLE` only for products that were retrieved without using the `SUSTAINABILITY_FILTER`.
> 
> https://github.com/calgo-lab/green-db/blob/7ab12c99ef0a6360540dbcc7129fa757f6235312/scraping/scraping/spiders/_base.py#L307-L314

Thanks Alex,

But my assumption would be that before the UNAVAILABLE label was added, we scraped for (paginated) pages which contained products without any sustainability info, although we had our filter `"?nachhaltigkeit=alle-nachhaltigen-artikel"` set already. So in the past that would result in not passing the constraint for a  non-empty sustainability_labels field, and thus those products were always scraped, but never extracted in the greendb.

So, in my opinion it would be better to resolve that (the pagination?) issue, and maybe avoid scraping unnecessary pages in the first place.
What do you think?
