### ISSUE TITLE
make patch-version not working on windows

### ISSUE THREAD

**Issue by BigDatalex** [calgo-lab/green-db#43]
`make patch-version` throws an error when executed on windows. The error is related to the `sed` command. The command yields the following error:
```
sed -i '' -e 's/0.1.7/0.1.8/' ../infrastructure/charts/workers/Chart.yaml
sed: can't read : No such file or directory
```
The command without the `-i ''` works on windows:
`sed -e 's/0.1.7/0.1.8/' ../infrastructure/charts/workers/Chart.yaml`

**Comment by en-GB** [comment]
fix in #44
