### ISSUE TITLE
Zalando extractor fails to extract sustainability labels

### ISSUE THREAD

**Issue by en-GB** [calgo-lab/green-db#74]
We used to extract labels directly from the rendered HTML.
Since Splash is no longer able to render zalando product pages, we extract them from this json file
https://github.com/calgo-lab/green-db/blob/bf77115617dc68cc91ba6c2cfdb3a79588ec0e26/extract/extract/extractors/zalando.py#L152
but occasionally some labels will be missing.
This only affects ~10 products in any given run and ive only seen it happen on zalando.co.uk.

Switching the zalando scraper to Playwright would probably fix it tho.

**Comment by se-jaeger** [comment]
With the latest changes from #79 the extractor can't find any sustainability labels leading to not create products.

**Comment by BigDatalex** [comment]
I just updated the zalando extractor. It was just a minor change, due to a change of a class name in the html. See: https://github.com/calgo-lab/green-db/commit/53601e8d5c9908e63c04559bdd5d5bc806753471

**Comment by BigDatalex** [comment]
There are two commits from @en-GB that might be more robust and improve the extraction of the zalando sustainability-labels see: 
- https://github.com/calgo-lab/green-db/pull/79/commits/a24c6ee6190a72b42159acc820d8802680ec50f9
- https://github.com/calgo-lab/green-db/pull/79/commits/990d08d2e4a39d7bad33f38068b126b6dd9effa9

We (@en-GB) should check if these behave the same (extract the same sustainability-labels) like in the original approach or if there are some implications. So far, for our zalando tests, these achieve the same results.

**Comment by se-jaeger** [comment]
@en-GB what's the status about this one? Ist this still an issue or can we just close it? Especially after the lates changes #83
