### ISSUE TITLE
Amazon 'description' can contain an empty string

### ISSUE THREAD

**Issue by BigDatalex** [calgo-lab/green-db#81]
I just noticed, that the `description` for a lot of amazon products contains an **empty string**. Is this intentional? A quick analysis showed that we have an empty description for 2437 of 10393 unique urls/ products.

The empty string is set in this return method:
https://github.com/calgo-lab/green-db/blob/258403381ee5916527a770f6f7e74a540f9d5cdb/extract/extract/extractors/amazon.py#L288-L296

This is one [example product](https://www.amazon.fr/HP-Chromebook-12b-ca0000sf-Ultraportable-Convertible/dp/B08RJGPSK6/ref=sr_1_8?qid=1656699722&refinements=p_n_cpf_eligible%3A22579881031&s=computers&sr=1-8) where this occured. Maybe it is possible to extend the description extractor and extract in case no description is found the bullet points ("À propos de cet article"/ "About this product") ?

**Comment by felixbiessmann** [comment]
Yes, this is often the case - the relevant information is always the union of title, description and bulletpoints (which is the case in the above example)

**Comment by felixbiessmann** [comment]
that's amazing, would be great to have that in our data base, wasn't aware this is already available ... but maybe it's a bit more complicated to express that in our current label schema?

**Comment by BigDatalex** [comment]
I just sent it to Lena, so that she can add it to our list ;) But this label provides scores as doubles, so far we just had integers with a few levels. So it might be a little tricky to integrate and also to evaluate these scores for our `sustainability-labels-evaluation.csv` if we want to use the same precision. Lets wait for Lena's opinion, on how credible this one is and then we will see :)

**Comment by BigDatalex** [comment]
Sometimes amazon products neither have bullet points nor a product description. For example see [here](https://www.amazon.fr/Marc-OPolo-1-28406E-11-Normale/dp/B08V7PRJR9/ref=sr_1_47?c=ts&keywords=Sportswear%2Bhomme&qid=1661452036&refinements=p_n_cpf_eligible%3A22579881031&s=apparel&sr=1-47&ts_id=464810031&th=1&psc=1). So it is actually possible to have an empty description. 

If we do not want empty descriptions we could just use the product name again as a description or concatenate for example the name, price and currency.

**Comment by felixbiessmann** [comment]
Often the title is descriptive enough. I’d suggest to keep the option of having an empty string as description in the GreenDB and when using the description for example for ML prediction tasks, I’d concatenate the title and description.
