### ISSUE TITLE
Use Git subpath as dependencies instead of local paths

### ISSUE THREAD

**Issue by se-jaeger** [calgo-lab/green-db#94]
Finally, poetry allows to use git repo's subpath as dependency: https://python-poetry.org/docs/dependency-specification/#git-dependencies

We should switch to this feature for all packages because this would make it much easier to add, e.g., `database` package as dependency in repositories that are not part of this code. 

Steps:
- [ ] Update all local dependencies in all pyproject.toml files as follows: `core = {git = "https://github.com/calgo-lab/green-db", branch = "main", subdirectory = "core"}`

**Comment by BigDatalex** [comment]
Closing this one, due to the issues we would face during development when touching multiple packages, as explained here: https://github.com/calgo-lab/green-db/issues/94#issuecomment-1473840812
